/**
 * 
 */
package com.authenticator.authenticate.util;

/**
 * @author sagar.jadhav
 *
 */
public interface ErrorConstant {
	String E0118 = "E0118";
	String PASSWORD_MANDATORY = "E0609";
	String USERNAME_MANDATORY = "E0906";
	String LANGUAGECODE_MANDATORY = "LANGUAGECODE_MANDATORY";
	String HTTP_REQUEST_DETAILS_MANDATORY = "E0609";
	String CLIENTBROWSER_MANDATAORY = "CLIENTBROWSER_MANDATAORY";
	String CLIENT_IP_ADDRESS_MANDATAORY = "CLIENT_IP_ADDRESS_MANDATAORY";
	String CLIENT_OS_MANDATAORY = "CLIENT_OS_MANDATAORY";
	String REFERNCE_MANDATAORY = "REFERNCE_MANDATAORY";
	String USER_AGENT_MANDATAORY = "USER_AGENT_MANDATAORY";
	String FULL_URL_MANDATAORY = "FULL_URL_MANDATAORY";
	String ACCESS_TOKEN_MANDATORY = "ACCESS_TOKEN_MANDATORY";
	String PLATFORM_CODE_MANDATORY = "PLATFORM_CODE_MANDATORY";
	String CAPTCHA_VALUE_MANDATATORY = "E0906";
}
